### ISSUE TITLE
Infinity toast when play/pause track

### ISSUE THREAD

**Issue by codeforfunzz** [ucielsola/sud-player#5]
Hi
I found an issue on your project. When I click play/pause a track some time, it shown infinity toast message
![image](https://github.com/ucielsola/sud-player/assets/153375958/a109c45a-36cb-4269-a87f-f4c613e4388e)

**Comment by ucielsola** [comment]
@codeforfunzz thanks for raising this issue! I've completely removed the Toast component in the new version. This was comming from the player buttons, actually, since there wasn't any debouncing on them. That's also solved.
